djangofilter_demo/urls.py
from django.contrib import admin
from django.urls import path
from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index')

]

core/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    class GenreChoices(models.TextChoices):
        CRIME = 'C'
        NON_FICTION = 'N'
        OTHER = 'O'
        SCI_FI = 'S'
        
    name = models.CharField(max_length=128)
    price = models.FloatField()
    number_in_stock = models.PositiveIntegerField(default=0)
    genre = models.CharField(max_length=1, choices=GenreChoices.choices)
    author = models.ForeignKey("Author", on_delete=models.CASCADE)
        
        
class Author(models.Model):
    name = models.CharField(max_length=128)

core/forms.py
from django import forms

class BookNameFilterForm(forms.Form):
    name = forms.CharField()

core/views.py
from django.shortcuts import render
from core.models import Book
from core.filters import BookFilter

# Create your views here.
def index(request):
    book_filter = BookFilter(request.GET, queryset=Book.objects.all())
    context = {
        'form': book_filter.form,
        'books': book_filter.qs
    }
    return render(request, 'index.html', context)

core/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django</title>

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>
<body>
    <div class="container mt-4">
        {% block content %}
        {% endblock %}
    </div> 
</body>
</html>

core/templates/index.html
{% extends 'base.html' %}

{% block content %}

<form method="GET" action="{% url 'index' %}">
    {{ form.as_p }}
    <input type="submit" value="Submit" class="btn btn-primary"/>
</form>

</hr>

<h1> Book List</h1>

<table class="table">
    <thead>
    <tr>
        <th>Name</th>
        <th>Author</th>
        <th>Genre</th>
        <th>Price</th>
    </tr>
    </thead>
    <tbody>
        {% for book in books %}
            <tr>
                <td>{{ book.name }}</td>
                <td>{{ book.author.name }}</td>
                <td>{{ book.get_genre_display }}</td>
                <td>{{ book.price }}</td>
            </tr>
        {% endfor %}
    </tbody>
{% endblock %}